name: CI

on: # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        model: ['lasso', 'multiclass-svm']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        products: Statistics_and_Machine_Learning_Toolbox

    - name: Cache downloaded data
      id: cache-data
      uses: actions/cache@v3
      with:
        path: data
        key: ${{ runner.os }}-data

    - name: Download Data
      run: |
        mkdir -p data
        cd data
        wget -q ${{ secrets.DOWNLOAD_URL }}
        cd ..

    - name: Run and test accuracy
      uses: matlab-actions/run-command@v2
      with:
        command: |
          tic
          acc = crossValidateSingleDataset('data', 2, 10, 0.1, 0.2, -0.2, inf, '${{ matrix.model }}', nan, 100, [0, inf])
          toc
          assert(acc>0.35)